/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DiaryImport } from './routes/diary'
import { Route as CvImport } from './routes/cv'
import { Route as LayoutImport } from './routes/_layout'
import { Route as IndexImport } from './routes/index'
import { Route as NotesIndexImport } from './routes/notes/index'
import { Route as NotesLayoutImport } from './routes/notes/_layout'
import { Route as NotesYearIndexImport } from './routes/notes/$year/index'
import { Route as NotesYearMonthImport } from './routes/notes/$year/$month'

// Create Virtual Routes

const NotesImport = createFileRoute('/notes')()

// Create/Update Routes

const NotesRoute = NotesImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRoute,
} as any)

const DiaryRoute = DiaryImport.update({
  id: '/diary',
  path: '/diary',
  getParentRoute: () => rootRoute,
} as any)

const CvRoute = CvImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const NotesIndexRoute = NotesIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NotesRoute,
} as any)

const NotesLayoutRoute = NotesLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => NotesRoute,
} as any)

const NotesYearIndexRoute = NotesYearIndexImport.update({
  id: '/$year/',
  path: '/$year/',
  getParentRoute: () => NotesRoute,
} as any)

const NotesYearMonthRoute = NotesYearMonthImport.update({
  id: '/$year/$month',
  path: '/$year/$month',
  getParentRoute: () => NotesRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/cv': {
      id: '/cv'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof CvImport
      parentRoute: typeof rootRoute
    }
    '/diary': {
      id: '/diary'
      path: '/diary'
      fullPath: '/diary'
      preLoaderRoute: typeof DiaryImport
      parentRoute: typeof rootRoute
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesImport
      parentRoute: typeof rootRoute
    }
    '/notes/_layout': {
      id: '/notes/_layout'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesLayoutImport
      parentRoute: typeof NotesRoute
    }
    '/notes/': {
      id: '/notes/'
      path: '/'
      fullPath: '/notes/'
      preLoaderRoute: typeof NotesIndexImport
      parentRoute: typeof NotesImport
    }
    '/notes/$year/$month': {
      id: '/notes/$year/$month'
      path: '/$year/$month'
      fullPath: '/notes/$year/$month'
      preLoaderRoute: typeof NotesYearMonthImport
      parentRoute: typeof NotesImport
    }
    '/notes/$year/': {
      id: '/notes/$year/'
      path: '/$year'
      fullPath: '/notes/$year'
      preLoaderRoute: typeof NotesYearIndexImport
      parentRoute: typeof NotesImport
    }
  }
}

// Create and export the route tree

interface NotesRouteChildren {
  NotesLayoutRoute: typeof NotesLayoutRoute
  NotesIndexRoute: typeof NotesIndexRoute
  NotesYearMonthRoute: typeof NotesYearMonthRoute
  NotesYearIndexRoute: typeof NotesYearIndexRoute
}

const NotesRouteChildren: NotesRouteChildren = {
  NotesLayoutRoute: NotesLayoutRoute,
  NotesIndexRoute: NotesIndexRoute,
  NotesYearMonthRoute: NotesYearMonthRoute,
  NotesYearIndexRoute: NotesYearIndexRoute,
}

const NotesRouteWithChildren = NotesRoute._addFileChildren(NotesRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof LayoutRoute
  '/cv': typeof CvRoute
  '/diary': typeof DiaryRoute
  '/notes': typeof NotesLayoutRoute
  '/notes/': typeof NotesIndexRoute
  '/notes/$year/$month': typeof NotesYearMonthRoute
  '/notes/$year': typeof NotesYearIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof LayoutRoute
  '/cv': typeof CvRoute
  '/diary': typeof DiaryRoute
  '/notes': typeof NotesIndexRoute
  '/notes/$year/$month': typeof NotesYearMonthRoute
  '/notes/$year': typeof NotesYearIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRoute
  '/cv': typeof CvRoute
  '/diary': typeof DiaryRoute
  '/notes': typeof NotesRouteWithChildren
  '/notes/_layout': typeof NotesLayoutRoute
  '/notes/': typeof NotesIndexRoute
  '/notes/$year/$month': typeof NotesYearMonthRoute
  '/notes/$year/': typeof NotesYearIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/cv'
    | '/diary'
    | '/notes'
    | '/notes/'
    | '/notes/$year/$month'
    | '/notes/$year'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/cv'
    | '/diary'
    | '/notes'
    | '/notes/$year/$month'
    | '/notes/$year'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/cv'
    | '/diary'
    | '/notes'
    | '/notes/_layout'
    | '/notes/'
    | '/notes/$year/$month'
    | '/notes/$year/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRoute
  CvRoute: typeof CvRoute
  DiaryRoute: typeof DiaryRoute
  NotesRoute: typeof NotesRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRoute,
  CvRoute: CvRoute,
  DiaryRoute: DiaryRoute,
  NotesRoute: NotesRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_layout",
        "/cv",
        "/diary",
        "/notes"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_layout": {
      "filePath": "_layout.tsx"
    },
    "/cv": {
      "filePath": "cv.tsx"
    },
    "/diary": {
      "filePath": "diary.tsx"
    },
    "/notes": {
      "filePath": "notes",
      "children": [
        "/notes/_layout",
        "/notes/",
        "/notes/$year/$month",
        "/notes/$year/"
      ]
    },
    "/notes/_layout": {
      "filePath": "notes/_layout.tsx",
      "parent": "/notes"
    },
    "/notes/": {
      "filePath": "notes/index.tsx",
      "parent": "/notes"
    },
    "/notes/$year/$month": {
      "filePath": "notes/$year/$month.tsx",
      "parent": "/notes"
    },
    "/notes/$year/": {
      "filePath": "notes/$year/index.tsx",
      "parent": "/notes"
    }
  }
}
ROUTE_MANIFEST_END */
